eureka:
  instance:
#    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://152.67.205.195:8761/eureka

# log level Setting
logging:
  level:
    org.hibernate.type: trace
    org.springframework.jdbc.core: trace


mosinsa:
  topic:
    order: 
      create: mosinsa-order-create
      cancel: mosinsa-order-cancel
    customer:
      create: mosinsa-customer-create
    promotion:
      participate: mosinsa-promotion-participate
    reaction:
      react: mosinsa-reaction-react
      cancel: mosinsa-reaction-cancel
  base-url: "http://152.67.205.195:8000"

token:
  access:
    secret: access_secret
    expiration: 3600000
#    expiration: 10000
  refresh:
    secret: refresh_secret
    expiration: 1209600000
