eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

# log level Setting
logging:
  level:
    org.hibernate.type: trace
    org.springframework.jdbc.core: trace


mosinsa:
  topic:
    order: 
      create: mosinsa-order-create
      cancel: mosinsa-order-cancel
      commit: mosinsa-order-commit
      rollback: mosinsa-order-rollback
    customer:
      create: mosinsa-customer-create
    promotion:
      participate: mosinsa-promotion-participate  
  base-url: "http://127.0.0.1:8000"
feignclient:
  url:
    customer: 127.0.0.1:8000/customer-service
    order: 127.0.0.1:8000/order-service
    product: 127.0.0.1:8000/product-service
    coupon: 127.0.0.1:8000/coupon-service


token:
  access:
    secret: access_secret
    expiration: 3600000
#    expiration: 10000
  refresh:
    secret: refresh_secret
    expiration: 1209600000
